version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: workflow_postgres
    environment:
      POSTGRES_DB: workflow_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret_password
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: